version: '3.9'
services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
<<<<<<< HEAD
      - CSCI3308-017Team01Tigers:/var/lib/postgresql/data
=======
      - group-project:/var/lib/postgresql/data
>>>>>>> fc6d6bcdbbfea1e64e76995c7271ad863eafaebe
      - ./src/init_data:/docker-entrypoint-initdb.d
  web:
    image: node:lts
    user: 'node'
    working_dir: /home/node/app
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./src:/home/node/app
    command: 'npm start'
volumes:
<<<<<<< HEAD
  CSCI3308-017Team01Tigers:
=======
  group-project:
>>>>>>> fc6d6bcdbbfea1e64e76995c7271ad863eafaebe
